### ISSUE TITLE
Synchronizer error on game launch: Item with the same key has already been added

### ISSUE THREAD

**Issue by Vyredrac** [Nexus-Mods/NexusMods.App#2869]
when installing new appimage for the upd i couldnt open the modmanager at all. With backups of my mods i didnt care about a reset so i deleted the Datafolder. I then went back into my account and added some mods back and pressed apply. Errors. I resetted the Datafolder again. When i try to launch the game with 1 mod im met with errors.

![Image](https://github.com/user-attachments/assets/6eaffb5c-51ba-4360-bd42-25f11ba2dae4)

[nexusmods.app.main.current.log](https://github.com/user-attachments/files/19304921/nexusmods.app.main.current.log)

[nexusmods.app.slim.current.log](https://github.com/user-attachments/files/19304935/nexusmods.app.slim.current.log)

**Comment by Vyredrac** [comment]
> Hi, this is strange but interesting, could you share what is inside your External Changes?

Hello! Ty for the reply!!! I actually resolved this issue on my own after digging into the logs more with a bunch of trials and errors i found it out. In the logs it showed the Launching Process was not happening "ERROR" due to this file 
{Game}/Data/Generated/Public/Shared/Assets/unique_tav/FACE/Skin_Atlas_Head_SHR_Tattoo_A_MSK.DDS

Unique Tav is a mod for BG3

I deleted the entire unique_tav folder and it worked afterwards (i re added all the mods).

Not sure why my NexusModsApp completely caved in tho when i deleted the appimage and downloaded the new one (This started all the problems)

**Comment by Al12rs** [comment]
We have identified the root cause of the issue released a hotfix for it:
https://github.com/Nexus-Mods/NexusMods.App/releases/tag/v0.8.3

After updating I would suggest clearing our your External Changes page to avoid any lingering issues.

**Comment by Al12rs** [comment]
- Fixed in: #2919

**Comment by Kar1O5** [comment]
Did a clean OS install, installed CP2077, downloaded the NMA appimage, added CP2077, didnt add any mods and I still get the same error. Don't know if I should do something else. I'm using Heroic Launcher.

```
System.ArgumentException: An item with the same key has already been added. Key: {Game}/engine/shader_final.cache
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at NexusMods.Abstractions.Loadouts.Synchronizers.ALoadoutSynchronizer.ReindexState(GameInstallation installation, IConnection connection, ITransaction tx) in /_/src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs:line 1181
   at NexusMods.Abstractions.Loadouts.Synchronizers.ALoadoutSynchronizer.ReindexState(GameInstallation installation, IConnection connection) in /_/src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs:line 1157
   at NexusMods.Abstractions.Loadouts.Synchronizers.ALoadoutSynchronizer.BuildSyncTree(ReadOnly loadout) in /_/src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs:line 361
   at NexusMods.Abstractions.Loadouts.Synchronizers.ALoadoutSynchronizer.Synchronize(ReadOnly loadout) in /_/src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs:line 867
   at NexusMods.Games.RedEngine.Cyberpunk2077.Cyberpunk2077Synchronizer.Synchronize(ReadOnly loadout) in /_/src/Games/NexusMods.Games.RedEngine/Cyberpunk2077/Cyberpunk2077Synchronizer.cs:line 64
   at NexusMods.DataModel.Synchronizer.SynchronizerService.Synchronize(LoadoutId loadoutId) in /_/src/NexusMods.DataModel/Synchronizer/SynchronizerService.cs:line 96
   at NexusMods.App.UI.LeftMenu.Items.ApplyControlViewModel.<Apply>b__32_0() in /_/src/NexusMods.App.UI/LeftMenu/Items/ApplyControl/ApplyControlViewModel.cs:line 128
   at NexusMods.App.UI.LeftMenu.Items.ApplyControlViewModel.Apply() in /_/src/NexusMods.App.UI/LeftMenu/Items/ApplyControl/ApplyControlViewModel.cs:line 126
   at NexusMods.App.UI.LeftMenu.Items.ApplyControlViewModel.<>c__DisplayClass31_0.<<-ctor>b__0>d.MoveNext() in /_/src/NexusMods.App.UI/LeftMenu/Items/ApplyControl/ApplyControlViewModel.cs:line 58
``` 

[nexusmods.app.main.00.log](https://github.com/user-attachments/files/19440622/nexusmods.app.main.00.log)
[nexusmods.app.main.current.log](https://github.com/user-attachments/files/19440623/nexusmods.app.main.current.log)
